import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const WC_AUTOLOADER_TEXT = `/**
 * wcf vendor runtime autoloader.
 *
 * importmap should map tagName (e.g. "myui-search-box")
 * to stable files under ./components/*.js.
 */

function collectCustomElementTagNames(root) {
  const out = new Set();
  const all = root.querySelectorAll('*');
  for (const el of all) {
    const name = String(el.localName || '').toLowerCase();
    if (!name.includes('-')) continue;
    out.add(name);
  }
  return [...out];
}

async function importTagNames(tagNames) {
  for (const tagName of tagNames) {
    try {
      // eslint-disable-next-line no-await-in-loop
      await import(tagName);
    } catch (e) {
      // eslint-disable-next-line no-console
      console.warn('[wcf-autoloader] Failed to import:', tagName, e);
    }
  }
}

async function runOnce() {
  const tagNames = collectCustomElementTagNames(document);
  await importTagNames(tagNames);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    runOnce();
  });
} else {
  runOnce();
}
`;

const BOOT_TEMPLATE_TEXT = `import { setConfig } from './components/config.js';
setConfig({ prefix: '__WCF_PREFIX__' });
await import('./wc-autoloader.js');
`;

const README_TEXT = `# vendor-runtime

This directory is generated by \`npm run vendor:build\`.

- \`src/**\`: transpiled ESM source from \`packages/**\` (non-bundle)
- \`elements/*.js\`: per-component define entrypoints
- \`registry.json\`: lightweight component/pattern registry for \`wcf\`
- \`boot.js\`: template used by \`wcf vendor install\` (prefix placeholder)
- \`wc-autoloader.js\`: importmap-based autoloader
`;

function findPackageRoot() {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, '..', '..');
}

function sortStrings(values) {
  return [...values].sort((a, b) => a.localeCompare(b));
}

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function writeText(filePath, text) {
  await ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, text, 'utf8');
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    stdio: 'inherit',
    ...options,
  });
  if (result.status !== 0) {
    throw new Error(`Command failed: ${command} ${args.join(' ')}`);
  }
}

async function readJson(filePath) {
  const text = await fs.readFile(filePath, 'utf8');
  return JSON.parse(text);
}

function failBuild(message) {
  throw new Error(`[vendor:build] ${message}`);
}

function parseImportedNames(rawNamedImports) {
  return rawNamedImports
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => {
      const match = item.match(/^([A-Za-z0-9_$]+)(?:\s+as\s+([A-Za-z0-9_$]+))?$/);
      return match?.[2] ?? match?.[1] ?? item;
    });
}

function pickDefineFunction({ sourceText, importedNames }) {
  const importedNameSet = new Set(importedNames);
  const calls = [...sourceText.matchAll(/\b(define[A-Za-z0-9_$]*)\s*\(/g)]
    .map((match) => match[1])
    .filter((name) => importedNameSet.has(name));

  if (calls.length > 0) return calls[0];
  return importedNames.find((name) => /^define[A-Za-z0-9_$]*$/.test(name)) ?? null;
}

async function loadRuntimeComponents(pkgRoot) {
  const autoloadRoot = path.join(pkgRoot, 'packages', 'autoload', 'dads');
  const entries = await fs.readdir(autoloadRoot, { withFileTypes: true });
  const files = entries.filter((entry) => entry.isFile() && entry.name.endsWith('.ts')).map((entry) => entry.name);
  const components = {};

  for (const fileName of sortStrings(files)) {
    const suffix = fileName.slice(0, -'.ts'.length);
    const absPath = path.join(autoloadRoot, fileName);
    // eslint-disable-next-line no-await-in-loop
    const sourceText = await fs.readFile(absPath, 'utf8');

    const importMatch = sourceText.match(/import\s*{([\s\S]*?)}\s*from\s*['"]([^'"]+)['"]/m);
    const relPath = path.posix.join('packages/autoload/dads', fileName);
    if (!importMatch) {
      failBuild(`${relPath}: expected a named import from ../../components/*/index.js`);
    }

    const rawNamedImports = importMatch[1];
    const fromPath = importMatch[2];
    if (!fromPath.startsWith('../../components/') || !fromPath.endsWith('/index.js')) {
      failBuild(`${relPath}: unexpected import path "${fromPath}"`);
    }

    const importedNames = parseImportedNames(rawNamedImports);
    const defineFn = pickDefineFunction({ sourceText, importedNames });
    if (!defineFn) {
      failBuild(`${relPath}: define* function not found in imported symbols`);
    }

    const defineModule = `src/${fromPath.slice('../../'.length)}`;
    components[suffix] = {
      tagBase: suffix,
      defineModule,
      defineFn,
    };
  }

  return components;
}

function resolveComponentClosure({ installRegistry, requiredIds }) {
  const installComponents = installRegistry?.components ?? {};
  const visited = new Set();
  const queue = [...requiredIds];

  while (queue.length > 0) {
    const nextId = queue.shift();
    if (!nextId || visited.has(nextId)) continue;
    const meta = installComponents[nextId];
    if (!meta || typeof meta !== 'object') {
      failBuild(`pattern requires unknown componentId: ${nextId}`);
    }

    visited.add(nextId);
    const deps = Array.isArray(meta.deps) ? meta.deps : [];
    for (const dep of deps) {
      if (typeof dep === 'string' && dep.trim() !== '') queue.push(dep.trim());
    }
  }

  return sortStrings(visited);
}

function componentIdToSuffixes({ componentId, installRegistry }) {
  const canonicalPrefix = String(installRegistry?.canonicalPrefix ?? 'dads').trim();
  const installComponents = installRegistry?.components ?? {};
  const meta = installComponents?.[componentId];
  if (!meta || typeof meta !== 'object') {
    failBuild(`componentId "${componentId}" does not exist in install-registry`);
  }

  const tags = Array.isArray(meta.tags) ? meta.tags : [];
  if (tags.length === 0) {
    failBuild(`componentId "${componentId}" has no tags in install-registry`);
  }

  const prefix = `${canonicalPrefix}-`;
  const suffixes = [];
  for (const rawTag of tags) {
    const tag = String(rawTag ?? '').trim().toLowerCase();
    if (!tag.startsWith(prefix)) {
      failBuild(`componentId "${componentId}" has non-canonical tag "${tag}"`);
    }
    const suffix = tag.slice(prefix.length);
    if (!suffix) {
      failBuild(`componentId "${componentId}" has invalid tag "${tag}"`);
    }
    suffixes.push(suffix);
  }

  return sortStrings(new Set(suffixes));
}

async function loadRuntimePatterns({ pkgRoot, runtimeComponents }) {
  const patternRegistryPath = path.join(pkgRoot, 'registry', 'pattern-registry.json');
  const installRegistryPath = path.join(pkgRoot, 'registry', 'install-registry.json');
  const patternRegistry = await readJson(patternRegistryPath);
  const installRegistry = await readJson(installRegistryPath);

  const patternsInput = patternRegistry?.patterns;
  if (!patternsInput || typeof patternsInput !== 'object') {
    failBuild('registry/pattern-registry.json: "patterns" must be an object');
  }

  const patterns = {};
  for (const patternId of sortStrings(Object.keys(patternsInput))) {
    const rawPattern = patternsInput[patternId];
    if (!rawPattern || typeof rawPattern !== 'object') {
      failBuild(`registry/pattern-registry.json: pattern "${patternId}" must be an object`);
    }

    const requires = Array.isArray(rawPattern.requires)
      ? rawPattern.requires.map((value) => String(value ?? '').trim()).filter(Boolean)
      : [];
    if (requires.length === 0) {
      failBuild(`pattern "${patternId}" must define non-empty requires[]`);
    }

    const directSuffixes = new Set();
    for (const componentId of requires) {
      for (const suffix of componentIdToSuffixes({ componentId, installRegistry })) {
        directSuffixes.add(suffix);
      }
    }

    const closureIds = resolveComponentClosure({ installRegistry, requiredIds: requires });
    const closureSuffixes = new Set();
    for (const componentId of closureIds) {
      for (const suffix of componentIdToSuffixes({ componentId, installRegistry })) {
        closureSuffixes.add(suffix);
      }
    }

    for (const suffix of closureSuffixes) {
      if (!runtimeComponents[suffix]) {
        failBuild(`pattern "${patternId}" references unavailable suffix "${suffix}"`);
      }
    }

    const entryHints = Array.isArray(rawPattern.entryHints)
      ? rawPattern.entryHints.map((value) => String(value ?? '').trim()).filter(Boolean)
      : [];

    patterns[patternId] = {
      id: patternId,
      title: String(rawPattern.title ?? patternId).trim() || patternId,
      description: String(rawPattern.description ?? '').trim(),
      components: sortStrings(closureSuffixes),
      requiredComponents: sortStrings(directSuffixes),
      stability: String(rawPattern.stability ?? 'stable').trim() || 'stable',
      contractVersion: String(rawPattern.contractVersion ?? '1.0').trim() || '1.0',
      entryHints: entryHints.length > 0 ? entryHints : ['boot'],
      sampleHtml: String(rawPattern.html ?? ''),
    };
  }

  return patterns;
}

async function generateElements(runtimeRoot, components) {
  const elementsDir = path.join(runtimeRoot, 'elements');
  await fs.rm(elementsDir, { recursive: true, force: true });
  await ensureDir(elementsDir);

  for (const suffix of sortStrings(Object.keys(components))) {
    const c = components[suffix];
    const code = `import { ${c.defineFn} } from '../${c.defineModule}';\n${c.defineFn}();\n`;
    // eslint-disable-next-line no-await-in-loop
    await writeText(path.join(elementsDir, `${suffix}.js`), code);
  }
}

async function generateRegistry(runtimeRoot, { components: runtimeComponents, patterns: runtimePatterns }) {
  const components = {};
  for (const suffix of sortStrings(Object.keys(runtimeComponents))) {
    const c = runtimeComponents[suffix];
    components[suffix] = {
      tagBase: c.tagBase,
      elementEntry: `components/${suffix}.js`,
      defineModule: c.defineModule,
      defineFn: c.defineFn,
    };
  }

  const patterns = {};
  for (const name of sortStrings(Object.keys(runtimePatterns))) {
    const p = runtimePatterns[name];
    patterns[name] = {
      id: name,
      title: p.title,
      description: p.description,
      components: [...p.components],
      requiredComponents: [...(p.requiredComponents ?? p.components)],
      stability: p.stability ?? 'stable',
      contractVersion: p.contractVersion ?? '1.0',
      entryHints: [...(p.entryHints ?? ['boot'])],
      sampleHtml: p.sampleHtml ?? '',
    };
  }

  const registry = {
    schemaVersion: 1,
    contractVersion: '1.0',
    deprecationPolicy: {
      graceCliMajorReleases: 1,
    },
    components,
    patterns,
  };

  await writeText(path.join(runtimeRoot, 'registry.json'), `${JSON.stringify(registry, null, 2)}\n`);
}

async function generateStaticFiles(runtimeRoot) {
  await writeText(path.join(runtimeRoot, 'wc-autoloader.js'), WC_AUTOLOADER_TEXT);
  await writeText(path.join(runtimeRoot, 'boot.js'), BOOT_TEMPLATE_TEXT);
  await writeText(path.join(runtimeRoot, 'README.md'), README_TEXT);
}

async function buildVendorRuntime({ check = false } = {}) {
  const pkgRoot = findPackageRoot();
  const runtimeRoot = path.join(pkgRoot, 'vendor-runtime');
  const runtimeSrc = path.join(runtimeRoot, 'src');
  const components = await loadRuntimeComponents(pkgRoot);
  const patterns = await loadRuntimePatterns({ pkgRoot, runtimeComponents: components });

  await ensureDir(runtimeRoot);
  await fs.rm(runtimeSrc, { recursive: true, force: true });

  const tscPath = path.join(pkgRoot, 'node_modules', 'typescript', 'bin', 'tsc');
  const tsconfigPath = path.join(pkgRoot, 'tsconfig.vendor-runtime.json');
  run(process.execPath, [tscPath, '-p', tsconfigPath], { cwd: pkgRoot });

  await generateElements(runtimeRoot, components);
  await generateRegistry(runtimeRoot, { components, patterns });
  await generateStaticFiles(runtimeRoot);

  if (check) {
    const diff = spawnSync('git', ['diff', '--quiet', '--', 'vendor-runtime'], {
      cwd: pkgRoot,
      stdio: 'ignore',
    });
    if (diff.status !== 0) {
      throw new Error('vendor-runtime is out of date. Run `npm run vendor:build` and commit changes.');
    }
  }
}

async function main() {
  const check = process.argv.includes('--check');
  await buildVendorRuntime({ check });
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error(String(error?.stack ?? error));
  process.exit(1);
});
